num1=int(input("Enter number1: "))
num2=int(input("Enter number2: "))
print("Addition: ",num1+num2)
print("Subtraction: ",num1-num2)
print("Multiplication: ",num1*num2)
print("Division: ",num1/num2)